version: '3'
services:
  timescale:
    image: 'timescale/timescaledb:latest-pg10'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - "3000:3000"
  consumer:
    environment:
      - PGUSER=postgres
      - PGHOST=timescale
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    build:
      dockerfile: Dockerfile.dev
      context: ./consumer
    volumes:
      - /app/node_modules
      - ./consumer:/app
